name: Lint
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]

    name: Lint
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install Pre-requisits on ubuntu
      run: |
        sudo apt-get -qy update
        sudo apt-get install g++ clang-tidy
        python -m pip install cmake ninja pytest numpy
        ninja --version
        cmake --version
        g++ --version
    - uses: actions/checkout@v3
    - name: cmake build
      run: |
        mkdir build
        cmake -Bbuild -DLIGO_TIDY=ON -S.
        cmake --build build/ --target ligo_tests
