name: Tests
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
        python: ["3.9", "3.10", "3.11"]

    name: Tests on ${{ matrix.os }} ${{ matrix.python }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/setup-python@v4
      id: python_setup
      with:
        python-version: ${{ matrix.python }}
    - name: check Python
      run: |
        which python
        echo ${{ env.pythonLocation }}
        python --version
    - name: Update CMake
      uses: jwlawson/actions-setup-cmake@v1.13
    - name: Install Python packages
      run: |
        python -m pip install ninja pytest numpy
        ninja --version
        cmake --version
    - name: Install Pre-requisits on ubuntu
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: |
        sudo apt-get -qy update
        sudo apt-get install g++
        g++ --version
    - uses: actions/checkout@v3
    - name: cmake configure
      run: cmake -Bbuild -S. -DPython_EXECUTABLE=${{ steps.python_setup.outputs.python-path }}
    - name: cmake build tests
      if: ${{ !startsWith(matrix.os, 'windows') }}
      run: cmake --build build/ --target ligo_tests -j 2
    - name: cmake build tests (windows)
      if: ${{ startsWith(matrix.os, 'windows') }}
      run: cmake --build build/ --target ligo_tests --config Release -j 2
    - name: Run tests
      run: pytest build
